name:                wavm-rpc-server
version:             0.1.0.0
github:              "LukeBillo/wavm-rpc-server"
license:             BSD3
author:              "Luke Billington"
maintainer:          "example@example.com"
copyright:           "2019 Luke Billington"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wavm-rpc-server#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- zeromq4-haskell
- bytestring
- MissingH

library:
  source-dirs: src
  extra-libraries:
    - stdc++
    - WAVM
    - wavm_runtime

executables:
  wavm-rpc-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wavm-rpc-server

tests:
  wavm-rpc-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wavm-rpc-server
